import type { Metadata } from "next";
import { Inter,Quicksand } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="703576097619-j4ceo8d829thp1tfedfnun45cmce6huu.apps.googleusercontent.com">
        <body className={inter.className}>{children}<Toaster/></body>
      </GoogleOAuthProvider>
    </html>
  );
}
